### ISSUE TITLE
Outline Phoneme Factory commands for various inputs

### ISSUE THREAD

**Issue by vnajack** [LoganParker/The-Speaking-Portal-Project#104]
**Is this related to a problem? Please describe.**
The Rhubarb tool's commands need to change depending on the user inputs. In preparation for when we receive these inputs, there should be a few if-statements to adjust the commands.

**Additional Context**
The following options will need to be specified for the commands:
- input file path
- language specifies which recognizer to use
- export format
- dialog text file path
- mouth shapes (6 basic of 9 extended)
- output file path

**Comment by LoganParker** [comment]
@vnajack I think you have completed this!

**Comment by vnajack** [comment]
didn't close automatically with PR #147, so I'm manually closing this issue.
