### ISSUE TITLE
readme update

### ISSUE THREAD

**Issue by edouarde1** [LoganParker/The-Speaking-Portal-Project#108]
**Describe what needs to get done**

The readme needs an update. It should include some information from our requirements gathering and a screenshot of the Gnatt Chart. 

We should also prep the readme with a table of contents for peer testing coming up in the next two weeks!

**Describe the solution you'd like**
A clear and concise description of how you would like it done.

**Additional context**

**Comment by vnajack** [comment]
I didn't include the screenshot because it's a weird shape on my screen. If you have a screenshot in mind and the shapes work out, please save it and I can add it!
