### ISSUE TITLE
Peer testing set-up

### ISSUE THREAD

**Issue by edouarde1** [LoganParker/The-Speaking-Portal-Project#119]
**Describe the solution you'd like**

For peer testing users will be able to input audio file and text file names that will be sent into our API. Since we do not have a UI, will be running a couple scenarios for user inputs to make sure our API can handle edge cases. Here were the scenarios we came up with as a group (feel free to change):

1) Scenario where the user enters no audio file or text file (FileNotFound situation)
2) Scenario where the user inputs a .mp3 file instead of a .wav file (Invalid file situation) 
3) Scenario where the user inputs a corrupted .wav file or .txt file (Corrupted file situation) 
4) Free for all scenario where the user can input whatever contents they would like

**Requirements for delivery**

1) Process for users to define inputs that can be extracted and sent into our main process 
- check out: process.env 

2) Directory of files in the repo for peer testing that can test the above scenarios

3) Text file that describes the scenarios that will be read during peer testing and a process of the how peer testing should be conducted

**Comment by mkuelker** [comment]
A branch has been added on to this issue. Please check the development section of the issue.

**Comment by mkuelker** [comment]
Making a note, Please add the readme

**Comment by mkuelker** [comment]
Added Items. Opening PR

**Comment by mkuelker** [comment]
Reopening for adding updates to item

**Comment by mkuelker** [comment]
- Notes: Add update to ask for TXT save
- Have the user view the output MP4, and delete output.json
- File not found test needs to be updated/fixed
-unique file.wave should be set respectively 5 to chipmunk 6 to otherfile

**Comment by mkuelker** [comment]
Annnnddddd updates added.
