### ISSUE TITLE
Find new team meeting time 

### ISSUE THREAD

**Issue by mkuelker** [LoganParker/The-Speaking-Portal-Project#165]
**Is this related to a problem? Please describe.**
Team needs to find a new time to meet

**Describe the solution you'd like**
Use  whentomeet.com

**Comment by vnajack** [comment]
Scheduling is being organized through when2meet (link on Discord)
Once class schedules are finalized, we'll be able to decide on team meeting and client meeting times.

**Comment by mkuelker** [comment]
The client meeting time has been decided. We'll keep the same time as last semester.

**Comment by vnajack** [comment]
Our new team meeting time is Mondays at 10:00am, so I think we can close this issue!

**Comment by mkuelker** [comment]
Closes
