### ISSUE TITLE
Find new client meeting times

### ISSUE THREAD

**Issue by mkuelker** [LoganParker/The-Speaking-Portal-Project#166]
**Describe what needs to get done**
Talk with other groups to find a new meeting time

**Describe the solution you'd like**
A precise time to communicate with the client is optimal for all parties.

**Comment by vnajack** [comment]
Sounds like Fridays from 4pm-5pm still work for the majority of people!
I'll add my questions and comments into the client meeting minutes before and after those meetings.

**Comment by mkuelker** [comment]
Okay, Clossing issue.
