### ISSUE TITLE
Research Animation Realism Techniques 

### ISSUE THREAD

**Issue by mkuelker** [LoganParker/The-Speaking-Portal-Project#169]
**Is this related to a problem? Please describe.**
We need to find new solutions for adding additional realism to our animations. 

**Describe the solution you'd like**
A clean and robust technique for parsing emote indicators (Could be emoticons or punctuation). Indicators given with text prompts must be on time. 

**What aspects are unclear - what needs to be done, or how it should be accomplished?**
Not sure how the animation process will work with automated expressions put in. Not sure how emotion mapping will work in some unique scenarios.

**Comment by vnajack** [comment]
After working on the idle animation, looking up different poses, and discussing the implementation based on pauses, timing, and specific mouth positions, I feel comfortable closing this issue. Does anyone want to keep this one open?

**Comment by LoganParker** [comment]
Numerous PRs have been created to close this issue, I believe we're at a stage where research is complete - so closing for now.
