### ISSUE TITLE
Solve the ERRCONNREFUSED error

### ISSUE THREAD

**Issue by LoganParker** [LoganParker/The-Speaking-Portal-Project#170]
**Is this related to a problem? Please describe.**
ERRCONREFUSED Error message pops up when more than 4 requests are sent to the API concurrently (On Docker - but also happens hosting the api on my local machine). 

**Describe the solution you'd like**
We need to find out what is causing this issue, and then fix this bug.
**Requirements for delivery**
API must be able to handle as many concurrent requests as is sent to it, without causing error.

**Additional context**
I believe this issue is caused because each core is only able to process one request at a time, and so node is refusing requests when it cannot handle more - there should be some sort of queuing system we can implement

**Comment by LoganParker** [comment]
@edouarde1 concluded this is no longer an issue based on some load testing that he preformed, but we should now look into issues with processing time & server load

**Comment by vnajack** [comment]
@LoganParker @edouarde1  are we closing this issue as "won't fix" or are we keeping it open?
We have another issue for the processing time and load:
- #216

**Comment by mkuelker** [comment]
Closing due to non-issue, as @edouarde1 said this was a postman issue.

Dear Postman: we know you're probably making too much money to care about us, but please fix your buggy platform. Cheers.
