### ISSUE TITLE
Fix ffmpeg Error Handling

### ISSUE THREAD

**Issue by mkuelker** [LoganParker/The-Speaking-Portal-Project#174]
**Describe what needs to get done**
Update Error Handling so it actually works. 
![image](https://user-images.githubusercontent.com/61034256/213260010-429656de-c4c8-4f5a-b57c-d309cbf4e750.png)

**Comment by LoganParker** [comment]
Turns out that actually works - so it's uncommented and changed on the realism-testing branch
