### ISSUE TITLE
Figure out why postman is crashing

### ISSUE THREAD

**Issue by LoganParker** [LoganParker/The-Speaking-Portal-Project#191]
**Describe what needs to get done**
Postman screen turns blank when mp4 response is received. 

**Describe the solution you'd like**
a fix that prevents postman from crashing

**Comment by edouarde1** [comment]
UPDATE: Working when running Postman from the web using the Desktop Agent. Install [here](https://www.postman.com/downloads/postman-agent/)

Very annoying bug when configuring a working directory with the Desktop Agent Application. Refer to to this link to resolve:

https://community.postman.com/t/cant-select-file-at-form-data-make-sure-that-postman-can-read-files-inside-the-working-directory/16440/17


According to [Postman Support](https://support.postman.com/hc/en-us/articles/360025359014-Troubleshooting-steps-for-Postman-desktop-issues):

"this indicates that there might be a client-side issue with the Postman desktop app."

Going to try to follow the steps that have outlined and see if the resolve works!

**Comment by edouarde1** [comment]
Unfortunately the resolve did not work for me...

If someone could attempt to repeat these [steps](https://support.postman.com/hc/en-us/articles/360025359014-Troubleshooting-steps-for-Postman-desktop-issues) that would be helpful.

I might attempt to install a different version of postman and see what happens. Could also see this as being an FFMPEG issue, but weird how the output runs fine in the web app.

**Comment by edouarde1** [comment]
Looks like its a postman issue at the moment: https://github.com/postmanlabs/postman-app-support/issues/11629#issue-1535102542

**Comment by vnajack** [comment]
> Looks like its a postman issue at the moment: [postmanlabs/postman-app-support#11629 (comment)](https://github.com/postmanlabs/postman-app-support/issues/11629#issue-1535102542)

That's sad. At least we can still send the request and download the response, so it's not an issue that we're producing.

**Comment by mkuelker** [comment]
Do we know how long it will take postman to tackle the bug? We can use the web client in the meantime but I did like having the app ready to go on my PC.

**Comment by LoganParker** [comment]
Is this issue still open technically? We do know why postman is crashing... (problem with postman) so we could probably close this issue.

**Comment by mkuelker** [comment]
I'm going to close the issue. BTW `save and download` in the dropdown menu in postman still works and stops the app from crashing.
