### ISSUE TITLE
Re-organize and add types into our repo 

### ISSUE THREAD

**Issue by edouarde1** [LoganParker/The-Speaking-Portal-Project#192]
**Is this related to a problem? Please describe.**

We need to add new types into our TypeScript App. There are numerous areas we could implement TypeScript typings into our project. 

**Describe the solution you'd like**

Implement the following types: 
- Character selection variable 
- [Other] animation variables

**Comment by vnajack** [comment]
In pursuit of understanding types better before we do this, I started reading documentation:
https://www.typescriptlang.org/docs/handbook/2/objects.html

**Comment by vnajack** [comment]
- duplicate #181
closed the duplicate above, but the notes from it are below. Please note that many of these were addressed in a recent PR, so Avatar is now a class, but we can still implement types.

types.ts
- export type eyes = "_eyes0" | "_eyes1" | "eyes2"
- mouthCueProcessor.ts
- const eye_selection : eyes = "_eyes0"
- This might help if we would like to use eye selections throughout the app
- Shall we also include a characterSelect into a types.ts ?
- Breathing Phase should also be typed
