### ISSUE TITLE
[Exploration] Learn C++ to bypass rhubarb checks and speed up processing time

### ISSUE THREAD

**Issue by mkuelker** [LoganParker/The-Speaking-Portal-Project#201]
**Is this related to a problem? Please describe.**
Apparently, there is a way to hack rhubarb source code to speed up the animation process. Problem is that none of us are C++ developers and currently we haven't the faintest idea how rhubarbs' backend actually works... save for a couple of CMake files. 
 
**Describe the solution you'd like**
1. Learn enough C++ to get by and modify the source code. 
(Likely will involve a bit of reverse engineering rhubarb to understand what exactly is going on. )
2. Build a new rhubarb.exe based off our modifications to the rhubarb team's work. 

**Describe the feature**
The ability to bypass language checks to speed up processing. 

**What aspects are unclear - what needs to be done, or how it should be accomplished?**
Currently, we don't know how C++ is working with rhubarb. Also, we need to talk to Daniel Wolf and figure out his suggested fix.

**Comment by mkuelker** [comment]
Source Code download here: https://github.com/DanielSWolf/rhubarb-lip-sync/archive/refs/tags/v1.13.0.zip

**Comment by mkuelker** [comment]
I'm considering closing the task after our current emails with Daniel.

**Comment by vnajack** [comment]
From the Rhubarb dev:

> Rhubarb tends to be used for games and similar media where speech usually comes one line at a time, a "line" rarely exceeding a single sentence. For those scenarios, it might be possible to hack Rhubarb to blindly trust the dialog and thus process faster. However, due to limitations in the speech processing libraries I use internally, this hack can only work for short audio clips without pauses in speech (in speech processing terms: audio files containing a single utterance each).

>Having listened to your sample files, I don't think this hack would be much use to you after all. Your original plan of using Rhubarb as-is or switching to the phonetic recognizer for speed reasons is probably best.

So it looks like this strategy won't work. Closing the issue.
