### ISSUE TITLE
Implement breathing (aka idle animation)

### ISSUE THREAD

**Issue by vnajack** [LoganParker/The-Speaking-Portal-Project#204]
**Describe the solution you'd like**
- A normal respiratory rate in healthy adults is roughly 12 to 20 breaths per minute
- Our avatars' breathing cycle will take 4 seconds, which results in ~15 breaths/min
- Proposed Breathing Phases:
  - 0 = rest
  - 1 = inhaling
  - 2 = lungs full
  - 3 = exhaling
  - Note: 1 and 3 are the same frame

**Requirements for delivery**
- function in code to implement the breathing
- file images for all breathing phases per mouth position

**Comment by LoganParker** [comment]
@vnajack closed via #255
