### ISSUE TITLE
Adjusting --maxThreads arg in Rhubarb in load testing

### ISSUE THREAD

**Issue by edouarde1** [LoganParker/The-Speaking-Portal-Project#216]
**Is this related to a problem? Please describe.**

We may be having a thread overload while running many Rhubarb instances. 

At the moment we are allowing Rhubarb too run on a maximum number of the threads. We should test to see if reducing the number of threads that Rhubarb occupies on each instance/request would increase the performance for concurrent requests. 

**Describe the solution you'd like**

Generate three tests in JMeter while adjusting the --maxThread arg in the Phoneme Factory for each test:
- 6 Requests @ 1 thread 
- 6 Requests @ half-max thread
- 6 Requests @ max-thread

Save results in a .csv file and generate some fun excel graphs! 

**Additional context**
 
If there are more efficient results by reducing the thread count we should consider changing the way Rhubarb performs thread assignment. 

A dynamic resolve could be to:

#of requests / maxNumber of Threads (or something like that)

BUT also I could be wrong and we might want to consider other solutions in increasing perfomance of our process

**Comment by mkuelker** [comment]
Added tons of work. This issue should be ready to clsoe soon.
