### ISSUE TITLE
Figure out why PNGs are distorted when exported using the photoshop script

### ISSUE THREAD

**Issue by LoganParker** [LoganParker/The-Speaking-Portal-Project#220]
**Describe what needs to get done**
We should try to figure out why the pngs are being distorted by ffmpeg when they are exported via photoshop. I have a suspicion that it could be my .psd file - but it could also be the script.

Interestingly, photoshop seems to refuse to export some of the frames when I attempt to export them via the timeline method, which leads me to believe its a problem with my psd file or my computer

**Comment by vnajack** [comment]
I tried re-exporting the .ai file to .psd, so we'll see if the file was corrupted or something from the last time it was exported

**Comment by LoganParker** [comment]
This was an error with the photoshop script not maintaining artboard size. Converting it to an illustrator script seems to have made our lives a lot easier as the illustrator scripting package is much better documented.
