### ISSUE TITLE
Have node app persist after ssh session is closed

### ISSUE THREAD

**Issue by mkuelker** [LoganParker/The-Speaking-Portal-Project#239]
**Is this related to a problem? Please describe.**
NPM start doesn't persist after the API is closed. This is because Linux has foreground and background processes apparently. There are several ways to deal with this issue but the most promising is `npm forever` which allows applications to persist after terminating the putty session. The only problem that the forever package doesn't work with npm start. My guess is it has something to do with packages.json.  Definetly will be picking @LoganParker 's brain on this one. 

**Describe the solution you'd like**
Have the application persist after ssh connection is closed.

**Comment by mkuelker** [comment]
This issue is pretty low priorty, as we can get past this and still run our servers and test them accordingly. 

I'm leaving this up however because our client would likely appreciate a server where they explore the API we're building

**Comment by vnajack** [comment]
Client developer indicated that the integration would be for them to do, we are closing this issue
