### ISSUE TITLE
Add directory checker to make sure rhubarb and ffmpeg is installed

### ISSUE THREAD

**Issue by mkuelker** [LoganParker/The-Speaking-Portal-Project#242]
**Is this related to a problem? Please describe.**
Nodejs can load and run our app without rhubarb or ffmpeg installed, and it doesn't always print those errors to terminal

**Describe the solution you'd like**
check directories first with some error handling

**Comment by vnajack** [comment]
Due to the fact that Rhubarb is still getting updates by its developers, we can't validate files due to the potential upcoming changes. Therefore, we will include error codes in the README to help developer users troubleshoot
