### ISSUE TITLE
Fix the Rhubarb Tests

### ISSUE THREAD

**Issue by edouarde1** [LoganParker/The-Speaking-Portal-Project#245]
**Is this related to a problem? Please describe.**

- Currently Rhubarb tests are not working because Rhubarb is not installed on the git runner

- Find command line install of Rhubarb and implement into tests

**Comment by LoganParker** [comment]
@edouarde1 try this from @mkuelker's ubuntu script:
> 
> cd **Desired Install Directory**
> sudo apt update
>  sudo apt-get install unzip
>  curl -LO https://github.com/DanielSWolf/rhubarb-lip-sync/releases/download/v1.13.0/Rhubarb-Lip-Sync-1.13.0-Linux.zip
>  unzip Rhubarb-Lip-Sync-1.13.0-Linux.zip
>  mv Rhubarb-Lip-Sync-1.13.0-Linux rhubarb
>  rm Rhubarb-Lip-Sync-1.13.0-Linux.zip

**Comment by edouarde1** [comment]
sweet! Thanks Logan, I didn't see this until now haha
