### ISSUE TITLE
Github workflow for PR, status check is very slow

### ISSUE THREAD

**Issue by edouarde1** [LoganParker/The-Speaking-Portal-Project#277]
**Is this related to a problem? Please describe.**

Tests complete, but merge not possible,

**Describe the solution you'd like**

Look into issue.

**Comment by edouarde1** [comment]
Looks like tests are taking ~3min to process. Need to reduce the load on tests.

**Comment by LoganParker** [comment]
> Looks like tests are taking ~3min to process. Need to reduce the load on tests.

for documentation updates we don't really need to run the system tests as they won't affect whether or not the system runs, can we just run them if there are files affected in a certain directory?
