### ISSUE TITLE
Peer Testing Report: Quantitative scores and bar graph

### ISSUE THREAD

**Issue by edouarde1** [LoganParker/The-Speaking-Portal-Project#288]
**Describe the solution you'd like**

- (20%) Average the quantitative scores you received from the participants in a bar graph with the 5 points on the y-axis and the 10 heuristics on the x-axis. Label your axes. Indicate the number of data points used in the graph. Be sure to explain the graph using the issues identified and any quoted comments you obtained from the participants. I'm expect an explanation for each one of the scores (i.e., why the team believe they got that score, how to improve it, whether or not it's important for their project, ...)

**Requirements for delivery**
A clear and concise description of all requirements of this task.

**Additional context**

**Comment by vnajack** [comment]
#294 
#293
