### ISSUE TITLE
Tooling documentation requires screenshot of illustrator layer setup

### ISSUE THREAD

**Issue by LoganParker** [LoganParker/The-Speaking-Portal-Project#290]
Just a simple screenshot 4 da docs :) @vnajack I believe you're the only one who still has access to illustrator so if you could do this that would be greatly appreciated!!

**Comment by vnajack** [comment]
Are these two okay, or are there other screenshots I should take?

![file-scripts-other script](https://user-images.githubusercontent.com/43711657/227420862-58251d19-319e-4e25-a93f-2babca6e8bb3.png)
![Layers](https://user-images.githubusercontent.com/43711657/227420863-96e1ed44-b847-42e9-8315-b7dbf5fe94a4.png)

**Comment by LoganParker** [comment]
> Are these two okay, or are there other screenshots I should take?
> 
> ![file-scripts-other script](https://user-images.githubusercontent.com/43711657/227420862-58251d19-319e-4e25-a93f-2babca6e8bb3.png) ![Layers](https://user-images.githubusercontent.com/43711657/227420863-96e1ed44-b847-42e9-8315-b7dbf5fe94a4.png)

Perfect! Not sure we need the first one, but its a nice to have!
