### ISSUE TITLE
Phoneme to MP4 Exploration

### ISSUE THREAD

**Issue by mkuelker** [LoganParker/The-Speaking-Portal-Project#97]
**Is this related to a problem? Please describe.**
We don't actually have any method in place to create our video and our animation

**Describe the solution you'd like**
Build a quick program with Typescript that can create an MP4 of our talking lips, or at least have a solid plan in place for how to build that program. 

**Describe the feature**
Preferably having an mp4 of talking mouth would be lovely. 

**What aspects are unclear - what needs to be done, or how it should be accomplished?**
Not sure how to take images and integrate them with rhubarb library to add animation. This will have to be researched.
Here are our two main questions. 
- How do we create an MP4 file with typescript?
- How do we have phoneme mapping to produce animation for our MP4 file?

**Comment by mkuelker** [comment]
https://www.youtube.com/watch?v=r1iul4uRFuE This approach already looks promising 

https://www.npmjs.com/package/svg-to-video

Goal: get an SVG converted to MP4 with svg-to-video

**Comment by LoganParker** [comment]
@mkuelker with the addition of ffmpeg, can this issue be closed? We now know how to generate MP4s via a list of phonemes... maybe a new issue can be opened for use of the SVG libraries?
