### ISSUE TITLE
Integrate Rhubarb package directory 

### ISSUE THREAD

**Issue by edouarde1** [LoganParker/The-Speaking-Portal-Project#99]
**Is this related to a problem? Please describe.**

For peer testing users should not have to install Rhubarb. This should be integrated into our local environment. 

**Describe the solution you'd like**

Rhubarb directory should be added and tested when running our app.

**Comment by vnajack** [comment]
- for peer testing, we will need both Windows and Mac OS versions
- will also need to confirm with Kukarella the OS of their server
- if we add the repo, our gitstats will be insane... will need to confirm with TA about this

**Comment by LoganParker** [comment]
> - for peer testing, we will need both Windows and Mac OS versions
> 
Could dockerizing our platform solve this?

**Comment by vnajack** [comment]
Ed moved the Rhubarb stuff into the speaking portal project directory (from the research directory). He tested it on his Mac laptop and confirmed it's working. I tested it on my Windows laptop, and it worked!
